Convert to PDK

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,53 +1,45 @@
 ---
+os: linux
+dist: xenial
 language: ruby
-
 cache: bundler
-
 before_install:
-  - if [ $BUNDLER_VERSION ]; then
-      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
-    fi
   - bundle -v
-  - rm Gemfile.lock || true
-  - gem update --system $RUBYGEMS_VERSION
+  - rm -f Gemfile.lock
+  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
+  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
+  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
+  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
   - gem --version
   - bundle -v
-
-sudo: false
-
-script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint strings:generate reference spec'
-
-matrix:
+script:
+  - 'bundle exec rake $CHECK'
+bundler_args: --without system_tests
+rvm:
+  - 2.5.7
+stages:
+  - static
+  - spec
+  - acceptance
+  -
+    if: tag =~ ^v\d
+    name: deploy
+jobs:
   fast_finish: true
   include:
-  - rvm: 2.4.4
-    env: PUPPET_GEM_VERSION="~> 5"
-  - rvm: 2.5.3
-    env: PUPPET_GEM_VERSION="~> 6"
-  - rvm: 2.4.4
-    sudo: required
-    services: docker
-    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
-    bundler_args:
-    script: bundle exec rake beaker
-  - rvm: 2.5.3
-    sudo: required
-    services: docker
-    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
-    bundler_args:
-    script: bundle exec rake beaker
-  - rvm: 2.4.4
-    sudo: required
-    services: docker
-    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5
-    bundler_args:
-    script: bundle exec rake beaker
-  - rvm: 2.5.3
-    sudo: required
-    services: docker
-    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6
-    bundler_args:
-    script: bundle exec rake beaker
-
+    -
+      env: CHECK="validate lint check rubocop"
+      stage: static
+    -
+      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
+      rvm: 2.5.7
+      stage: spec
+    -
+      env: DEPLOY_TO_FORGE=yes
+      stage: deploy
+branches:
+  only:
+    - main
+    - /^v\d/
 notifications:
   email: false
